In [ ]:
#numpy:--
'''numpy which stands for "numerical python " is a popular python library for numerical and scientific computing. It provide support for working with large, 
multi-dimensional arrays and matrices of data, along with a collection''' 
'''key features and aspects NumPy:
1.)Multi-dimensional array-
2.)Broadcasting
3.)Element-wise operator
4.)Mathematical Operator'''

In [6]:
import numpy as np
l=[10,20,30,40,50]
array=np.array(l)
print(array)

[10 20 30 40 50]


In [10]:
import numpy as np
a=np.array(1)
b=np.array([1,2,4,5])
c=np.array([[1,2,4,5],[2,4,7,9]])
d=np.array([[[1,2,4,5],[2,4,7,9]],[[8,9,7,6],[2,4,5,7]]])
print("a array is",a)
print("b array is",b)
print("c array is",c)
print("d array is",d)

a array is 1
b array is [1 2 4 5]
c array is [[1 2 4 5]
 [2 4 7 9]]
d array is [[[1 2 4 5]
  [2 4 7 9]]

 [[8 9 7 6]
  [2 4 5 7]]]


In [12]:
import numpy as np
a=np.array(1)                                                       #0 dimension
b=np.array([1,2,4,5])                                              #1 dimension
c=np.array([[1,2,4,5],[2,4,7,9]])                                   #2 dimension
d=np.array([[[1,2,4,5],[2,4,7,9]],[[8,9,7,6],[2,4,5,7]]])           #3 dimension
print("a array is",a)
print("b array is",b)
print("c array is",c)
print("d array is",d)

print("a array dimen",a.ndim)
print("b array dimen",b.ndim)
print("c array dimen",c.ndim)
print("d array dimen",d.ndim)

a array is 1
b array is [1 2 4 5]
c array is [[1 2 4 5]
 [2 4 7 9]]
d array is [[[1 2 4 5]
  [2 4 7 9]]

 [[8 9 7 6]
  [2 4 5 7]]]
a array dimen 0
b array dimen 1
c array dimen 2
d array dimen 3


In [14]:
import numpy as np
a=np.array(1)                                                       #0 dimension
b=np.array([1,2,4,5])                                              #1 dimension
c=np.array([[1,2,4,5],[2,4,7,9]])                                   #2 dimension
d=np.array([[[1,2,4,5],[2,4,7,9]],[[8,9,7,6],[2,4,5,7]]])           #3 dimension
print("a array is",a)
print("b array is",b)
print("c array is",c)
print("d array is",d)

print("a array dimen",a.ndim)
print("b array dimen",b.ndim)
print("c array dimen",c.ndim)
print("d array dimen",d.ndim)

print("a array shape",a.shape)
print("b array shape",b.shape)
print("c array shape",c.shape)
print("d array shape",d.shape)

a array is 1
b array is [1 2 4 5]
c array is [[1 2 4 5]
 [2 4 7 9]]
d array is [[[1 2 4 5]
  [2 4 7 9]]

 [[8 9 7 6]
  [2 4 5 7]]]
a array dimen 0
b array dimen 1
c array dimen 2
d array dimen 3
a array shape ()
b array shape (4,)
c array shape (2, 4)
d array shape (2, 2, 4)


In [16]:
#slicing array
import numpy as np
arr=np.array([1,2,3,4])
print(arr[3])

4


In [20]:
#slicing array with parameters start,end and steps
import numpy as np
arr=np.array([1,2,3,4,5,6,9,8,10])
print(arr[2:8:2])

[3 5 9]


In [34]:
#data types of numpy----->>>>>string,integer,float and boolean
import numpy as np
arr=np.array([1,2,3,4,5,6,9,8,10])
sarr=arr[3:10]
print(arr)
print(sarr)
sarr[5]=100
print(arr)
print(sarr)

[ 1  2  3  4  5  6  9  8 10]
[ 4  5  6  9  8 10]
[  1   2   3   4   5   6   9   8 100]
[  4   5   6   9   8 100]


In [38]:
##copy---
#if change in original array than it doesn't affect in new copied array.
import numpy as np
arr=np.array([1,2,3,4,5,6,9,8,10])
arr2=arr.copy()
arr[0]=42
print(arr)
print(arr2)

[42  2  3  4  5  6  9  8 10]
[ 1  2  3  4  5  6  9  8 10]


In [40]:
##view---
#if change in original array than it does affect in new copied array.
import numpy as np
arr=np.array([1,2,3,4,5,6,9,8,10])
arr2=arr.view()
arr[0]=42
print(arr)
print(arr2)

[42  2  3  4  5  6  9  8 10]
[42  2  3  4  5  6  9  8 10]


In [50]:
#numpy.zero() -> to set all the elements are to be zeroes
import numpy as np
arr=np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [52]:
#numpy.zero() without order in python
import numpy as np
arr=np.zeros((6,),dtype=int)
arr

array([0, 0, 0, 0, 0, 0])

In [54]:
#numpy.zero() with shape in python
import numpy as np
arr=np.zeros((6,2))
arr


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [56]:
##numpy.ones() -> to set all the elements are to be ones
import numpy as np
arr=np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [58]:
#numpy.ones() without order in python
import numpy as np
arr=np.ones((6,),dtype=int)
arr

array([1, 1, 1, 1, 1, 1])

In [60]:
#numpy.ones() with shape in python
import numpy as np
arr=np.ones((6,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
##numpy.eye() return 2D array with 1's as diagonally and 0's elsewhere.
import numpy as np
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [64]:
import numpy as np
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [70]:
##numpy.diag() to return different elements to the diagonal of array
import numpy as np
arr=np.diag((3,1,2,4))
print(arr)
print(arr.ndim)
print(arr.shape)



[[3 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 4]]
2
(4, 4)
