In [4]:
'''randint() -> is an inbuilt function of thr random module in python3. The randommodule gives access to various useful function one of them being able to
generate random numbers, which is randint()'''
import numpy as np
rand=np.random.randint(0,10,2)
print(rand)

[7 1]


In [6]:
import numpy as np
rand=np.random.randint(4)
print(rand)
rand=np.random.rand(2,3)
print(rand)

3
[[0.45856976 0.75485589 0.68527918]
 [0.15865699 0.47271129 0.53991918]]


In [12]:
import numpy as np
arr=np.random.randint(0,100,10)
print(arr)

[50 95 57  6 66 56 14 84 14 46]


In [20]:
'''reshape function in numpy allows you to change the shape(dimension) of an array without changing its data. This can be useful when want to reaarange 
the way data is orgainized in ana array,such as converting a 1-dimensional array into a 2-dimensional matrix or vice-versa,or changing the size of a 
multi-dimensional array while maintaining the total number of elements.'''
import numpy as np
arr=np.array([1,2,3,4,5,50])
print(arr)
arr2=arr.reshape(3,2)
print(arr2)

[ 1  2  3  4  5 50]
[[ 1  2]
 [ 3  4]
 [ 5 50]]


In [43]:
import numpy as np
arr=np.random.randint(0,100,12)
print(arr)
arr=arr.reshape(4,3)
print(arr)
print("array value is" ,arr[0][1])
print("array value is" ,arr[1][0])
print(arr.shape)
arr=arr.reshape(-1,4)
print(arr)
arr=arr.reshape(2,-1)
print(arr)

[21 69 26 80 61 38 55 14 55 37 23 94]
[[21 69 26]
 [80 61 38]
 [55 14 55]
 [37 23 94]]
array value is 69
array value is 80
(4, 3)
[[21 69 26 80]
 [61 38 55 14]
 [55 37 23 94]]
[[21 69 26 80 61 38]
 [55 14 55 37 23 94]]


In [45]:
##seed function
import numpy as np
np.random.seed(145)
arr=np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [47]:
import numpy as np
np.random.seed(145)
arr=np.random.randint(0,500,30).reshape (6,5)
print(arr)

[[ 37 106 379 470 471]
 [146  90 453   8 309]
 [289 242 160 168 154]
 [468 101  29  10 111]
 [109   8 473  33 390]
 [279 390 365 168 322]]


In [49]:
import numpy as np
np.random.seed(145)
arr=np.random.randint(0,500,30).reshape (6,5)
print(arr[2:,2:])

[[160 168 154]
 [ 29  10 111]
 [473  33 390]
 [365 168 322]]


In [51]:
import numpy as np
np.random.seed(145)
arr=np.random.randint(0,500,30).reshape (6,5)
print(arr[3:5,2:4])

[[ 29  10]
 [473  33]]


In [57]:
import numpy as np
arr=np.array([1,20,3,5,6,7,7,88,8,9,9,3,43,45,5665,566,778])
slicing=arr[4:9]
print("new slicing", slicing)
print("new array" ,arr)
print(type(slicing))
print(type(arr))
slicing[:]=0
print("old slicing" ,slicing)
print("old array" ,arr)

new slicing [ 6  7  7 88  8]
new array [   1   20    3    5    6    7    7   88    8    9    9    3   43   45
 5665  566  778]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old slicing [0 0 0 0 0]
old array [   1   20    3    5    0    0    0    0    0    9    9    3   43   45
 5665  566  778]


In [66]:
#arange() is used to generate sequence
import numpy as np
arr=np.arange(1,15)
print(arr)
print(arr[arr%2==0])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [68]:
import numpy as n
ar=n.arange(1,15)
print(ar)
print(ar[arr%2==0])
print(ar[ar%2==0])
print(ar[ar>8])
ar[ar%2==0]=0
print(ar)
ar=n.arange(1,8)
print(arr+2)
print(arr*2)
print(arr**2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 2  4  6  8 10 12 14]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[  1   4   9  16  25  36  49  64  81 100 121 144 169 196]


In [72]:
import numpy as np
arr=np.array([10,20,30,25,6,2])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))


2
30
5
2
[3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


In [82]:
import numpy as np
np.random.seed(122)
mat=np.random.randint(1,31,9).reshape(3,3)
print(mat)
print(np.sum(mat))
print(np.cumsum(mat))
print(np.min(mat))
print(np.max(mat))
print("-------------")
print(np.sum(mat,axis=1))
print(np.cumsum(mat,axis=1))
print(np.min(mat,axis=1))
print(np.max(mat,axis=1))


[[16 27 11]
 [23 13 17]
 [13 16 28]]
164
[ 16  43  54  77  90 107 120 136 164]
11
28
-------------
[54 53 57]
[[16 43 54]
 [23 36 53]
 [13 29 57]]
[11 13 13]
[27 23 28]


In [86]:
import numpy as np
np.random.seed(122)
mat=np.random.randint(1,21,10)
print(mat)
np.random.shuffle(mat)
print(mat)
print(np.unique(mat,return_index=True,return_counts=True))
print(np.unique(mat).size)

[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))
6
