In [7]:
'''Split () function:->  the np.split() function is used to split an array into multiple sub-arrays along a
specified axis. '''
import numpy as np
#split the array into 3 equal-sized sub-arrays
arr=np.array([1,2,3,4,5,6])
#print subarrays
sub_arrays=np.split(arr,2)
for sub_arr in sub_arrays:
    print(sub_arr)

[1 2 3]
[4 5 6]


In [11]:
'''sort():->  In NumPy, you can use the np.sort() function to sort elements in an array along a specified axis. This function returns a sorted copy of
the original array.'''
import numpy as np
arr=np.array([3,1,4,6,8,9])
sorted_array=np.sort(arr)
print("sorted array(ascending)",sorted_array)
sorted_array_desc=np.sort(arr)[::-1]
print("sorted array(descending)",sorted_array_desc)

sorted array(ascending) [1 3 4 6 8 9]
sorted array(descending) [9 8 6 4 3 1]


In [13]:
#Sorting Along Specific Axis
import numpy as np
matrix=np.array([[3,1,2],[6,5,4]])
sorted_matrix=np.sort(matrix,axis=1)
print("sorted matrix(ascending along rows):")
print(sorted_matrix)

sorted matrix(ascending along rows):
[[1 2 3]
 [4 5 6]]


In [27]:
#join NumPy, you can concatenate (join) multiple arrays along specified axes using various functions


##   1.)concatenation- np.concatenate() function is used to join arrays along a specified axis


#             a.)horizontally contatenation
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)


#              a.)vertically contatenation
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
# Concatenate arr1 and arr2 along rows (vertical)
result = np.concatenate((arr1, arr2), axis=0)
# Print the concatenated array
print(result)



[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [31]:
#              c.) np.vstack() and np.hstack():



#np.vstack()
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Stack arr1 and arr2 vertically
result = np.vstack((arr1, arr2))
# Print the vertically stacked array
print(result)


#np.hstack()
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
# Stack arr1 and arr2 horizontally
result = np.hstack((arr1, arr2))
# Print the horizontally stacked array
print(result)

[[1 2 3]
 [4 5 6]]
[1 2 3 4]


In [33]:
#filter():- you can filter elements in an array based on a specified condition using boolean indexing.
import numpy as np
# Exam scores for a class of students
scores = np.array([85, 92, 78, 88, 95, 72, 89, 94, 68, 90])
# Find students who scored above 90
above_90 = scores[scores > 90]
print("Students who scored above 90:", above_90)

Students who scored above 90: [92 95 94]


In [39]:
'''NumPy Statistical Functions'''
#np.mean() - Mean (Average): Calculates the average value of an array.
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
avg_array=np.mean(array)
print(avg_array)

5.5


In [45]:
#np.median() - Median: Finds the median value (middle value when sorted) of an array.
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
median_array=np.median(array)
print(median_array)

7.0


In [49]:
#np.std() - Standard Deviation: Standard Deviation is a statistical measure that quantifies the amount of variation or dispersion in a dataset.
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
mean_array=np.mean(array)
print("mean of array",mean_array)
std_array=np.std(array)
print("standard deviation of array", std_array)

mean of array 5.5
standard deviation of array 2.8722813232690143


In [51]:
#np.var() - Variance is a statistical measure that quantifies how data points in a dataset are spread out or dispersed from the mean (average).
array=np.array([1,2,3,4,5,6,7,8,9,10])
mean_array=np.mean(array)
print("mean of array",mean_array)
std_array=np.std(array)
print("standard deviation of array", std_array)
var_array=np.var(array)
print("variance of array",var_array)

mean of array 5.5
standard deviation of array 2.8722813232690143
variance of array 8.25


In [71]:
'''numpy.percentile(a, q):->
a: This is the input array or sequence for which you want to calculate the percentiles.
q: This parameter specifies the percentile(s) to be calculated'''

import numpy as np
test_scores=np.array([10,20,30,40,50,60,70,80,90,100,112,120,130,140,130,120,130,140,150,160,170])
q = np.percentile(test_scores, 25)
print("25th Percentile):", q)


q = np.percentile(test_scores, 50)
print("50th Percentile):", q)

q = np.percentile(test_scores, 75)
print("75th Percentile):", q)

25th Percentile): 60.0
50th Percentile): 112.0
75th Percentile): 130.0


In [73]:
#np.load() is a function in the NumPy library used to load data from a binary file
import numpy as np
scores=np.array([20,40,60,67,45,89,56,78,23,79])
np.save("student_scores.npy",scores)
loaded_scores=np.load('student_scores.npy')
print("original scores",scores)
print("loaded scores",loaded_scores)

original scores [20 40 60 67 45 89 56 78 23 79]
loaded scores [20 40 60 67 45 89 56 78 23 79]
